export type ConnectorType = "FILE_UPLOAD" | "SFTP" | "REST_API" | "ERP_NATIVE" | "DB" | "STREAM";
export type AuthScheme = "NONE" | "API_KEY" | "OAUTH2_CLIENT" | "BASIC" | "SFTP_KEY";
export type ExtractionMode = "FULL" | "INCREMENTAL_DATE" | "INCREMENTAL_SEQ" | "EVENT_DRIVEN";

export interface DatasetDescriptor {
  id: string;
  label: string;
  canonicalMappings: string[];
}

export interface ConnectorManifest {
  id: string;
  displayName: string;
  version: string;
  connectorType: ConnectorType;
  authScheme: AuthScheme;
  extractionModes: ExtractionMode[];
  supportedDatasets: DatasetDescriptor[];
  maxFileSizeMb: number | null;
  maxRowsPerJob: number | null;
  rateLimit: { requestsPerMin: number; burst: number } | null;
  idempotencyKey: string;
  requiresColumnMap: boolean;
}

export type ConnectorErrorCode = "CE-001" | "CE-002" | "CE-003" | "CE-004" | "CE-005" | "CE-006";

export class ConnectorError extends Error {
  constructor(
    public code: ConnectorErrorCode,
    message: string,
    public retryable: boolean,
    public details?: any
  ) {
    super(message);
    this.name = "ConnectorError";
  }
}

export interface TestResult {
  ok: boolean;
  latencyMs: number;
  error?: ConnectorError;
}

export interface ExtractionJob {
  jobId: string;
  connectorId: string;
  orgId: string;
  entityId: string;
  config: Record<string, any>;
  filePaths?: string[]; // For FILE_UPLOAD connectors
  dateRange?: { start: Date; end: Date };
}

export interface RawRecord {
  _sourceId?: string;
  [key: string]: any;
}

export interface ExtractionResult {
  jobId: string;
  rawRecords: RawRecord[];
  totalParsed: number;
  warnings?: string[];
}

export type DocType = "INVOICE" | "CREDIT_NOTE" | "DEBIT_NOTE" | "PAYMENT" | "JOURNAL" | "OTHER";

export interface CanonicalTransactionInput {
  stableIdentityKey?: string; // Auto-generated by platform if omitted
  sourceConnectorId: string;
  sourceRecordId?: string;
  domainId: string;
  datasetLabel: string;
  
  docType: DocType;
  docNumber: string;
  docDate: Date;
  periodKey?: string; // Auto-generated if omitted
  
  counterpartyName?: string;
  counterpartyTaxId?: string;
  counterpartyId?: string;
  
  currencyCode: string;
  exchangeRate: number;
  netAmount: number;
  taxAmount?: number;
  grossAmount: number;
  
  baseNetAmount?: number; // Auto-generated if omitted
  baseTaxAmount?: number; // Auto-generated if omitted
  baseGrossAmount?: number; // Auto-generated if omitted
  
  accountCode?: string;
  costCentre?: string;
  referenceDocNumber?: string;
  lineItems?: any[];
  customFields?: Record<string, any>;
}

export interface TransformationResult {
  canonicalTransactions: CanonicalTransactionInput[];
  quarantinedRecords: any[];
  rejectedRecords: any[];
  errors: string[];
}

export interface ReportPayload {
  jobId: string;
  connectorId: string;
  startedAt: Date;
  completedAt: Date;
  rowsExtracted: number;
  rowsMapped: number;
  rowsQuarantined: number;
  rowsRejected: number;
  errors: string[];
  warnings: string[];
}

export interface ConnectorInterface {
  describe(): ConnectorManifest;
  test(): Promise<TestResult>;
  extract(job: ExtractionJob): Promise<ExtractionResult>;
  transform(raw: RawRecord[], jobContext: ExtractionJob): Promise<TransformationResult>;
  report(payload: ReportPayload): Promise<void>;
}
