"use client";

import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Filter, Search, FileArchive, Download, RefreshCw, Archive } from "lucide-react";
import { ColumnDef } from "@tanstack/react-table";
import Link from "next/link";
import { useState } from "react";

export type EvidencePackageRow = {
  id: string;
  period: string;
  status: "Ready" | "Generating" | "Pending" | "Failed" | "Expired";
  createdBy: string;
  createdAt: string;
  size: string;
  expiry: string;
};

const columns: ColumnDef<EvidencePackageRow>[] = [
  { accessorKey: "id", header: "Package ID", cell: ({ row }) => (
    <Link href={`/compliance/evidence-packages/${row.original.id}`} className="font-medium text-blue-600 hover:underline focus:outline-none focus:ring-2 focus:ring-blue-500 rounded-sm flex items-center gap-2">
      <FileArchive className="h-4 w-4 text-gray-400" />
      {row.getValue("id")}
    </Link>
  )},
  { accessorKey: "period", header: "Period", cell: ({ row }) => <span className="font-medium text-gray-900">{row.getValue("period")}</span> },
  { accessorKey: "status", header: "Status", cell: ({ row }) => {
      const status = row.getValue("status") as string;
      const variantMap: Record<string, "success" | "warning" | "destructive" | "neutral" | "secondary"> = {
        Ready: "success", Generating: "warning", Failed: "destructive", Pending: "neutral", Expired: "secondary"
      };
      return <StatusBadge variant={variantMap[status] || "neutral"}>{status}</StatusBadge>;
  }},
  { accessorKey: "createdBy", header: "Generated By" },
  { accessorKey: "createdAt", header: "Generated At" },
  { accessorKey: "size", header: "Size" },
  { accessorKey: "expiry", header: "Expiry", cell: ({ row }) => {
      const isExpired = row.getValue("status") === "Expired";
      return <span className={isExpired ? "text-red-600 font-medium" : "text-gray-600"}>{row.getValue("expiry")}</span>;
  }},
  { id: "actions", header: "Actions", cell: ({ row }) => {
      const status = row.getValue("status");
      return (
        <div className="flex items-center gap-2">
          {status === "Ready" && (
            <Button variant="outline" size="sm" className="h-7 text-xs text-blue-700 bg-blue-50 border-blue-200 hover:bg-blue-100">
              <Download className="mr-1 h-3 w-3" /> Download
            </Button>
          )}
          {(status === "Failed" || status === "Expired") && (
            <Button variant="outline" size="sm" className="h-7 text-xs">
              <RefreshCw className="mr-1 h-3 w-3" /> Regenerate
            </Button>
          )}
        </div>
      );
  }},
];

export function EvidencePackagesClient({ initialData }: { initialData: EvidencePackageRow[] }) {
  const [data] = useState(initialData);
  const [globalFilter, setGlobalFilter] = useState("");

  const hasData = data.length > 0;

  return (
    <div className="flex-1 bg-white border border-gray-200 rounded-xl shadow-sm flex flex-col overflow-hidden">
      <div className="p-4 border-b border-gray-200 flex justify-between items-center bg-gray-50 shrink-0">
        <h2 className="text-sm font-semibold text-gray-900">Evidence Packages</h2>
        <div className="flex items-center gap-3">
          <div className="relative w-[280px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" aria-hidden="true" />
            <Input 
              type="search"
              placeholder="Search Package ID, Period..." 
              className="pl-9 h-9"
              aria-label="Search evidence packages"
              value={globalFilter}
              onChange={(e) => setGlobalFilter(e.target.value)}
            />
          </div>
          <Button variant="outline" size="sm" className="h-9 border-gray-200 bg-white">
            <Filter className="mr-2 h-4 w-4 text-gray-500" aria-hidden="true" /> Filter
          </Button>
        </div>
      </div>
      
      <div className="p-4 flex-1 overflow-auto">
        {!hasData ? (
           <div className="flex flex-col items-center justify-center h-full text-center py-20">
             <Archive className="h-12 w-12 text-gray-300 mb-4" aria-hidden="true" />
             <h2 className="text-lg font-medium text-gray-900 mb-1">No evidence packages generated</h2>
             <p className="text-sm text-gray-500 mb-6">Packages aggregate transactions, exceptions, and audit logs for period-close.</p>
             <Button className="bg-blue-600 hover:bg-blue-700 text-white">
               Generate Package
             </Button>
           </div>
        ) : (
          <DataTable 
            columns={columns} 
            data={data.filter(row => 
              row.id.toLowerCase().includes(globalFilter.toLowerCase()) || 
              row.period.toLowerCase().includes(globalFilter.toLowerCase())
            )} 
            isServerSide={false} 
          />
        )}
      </div>
    </div>
  );
}
