/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, prefer-const, @typescript-eslint/no-empty-object-type, react/no-unescaped-entities, jsx-a11y/role-has-required-aria-props, react/jsx-no-undef, no-restricted-imports */
import { PageHeader } from "@/components/ui/page-header";
import { Breadcrumb } from "@/components/layout/breadcrumb";
import { StatusBadge } from "@/components/ui/status-badge";
import { Button } from "@/components/ui/button";
import { EvidenceDetailClient } from "@/components/compliance/evidence-detail-client";
import { Download, RefreshCw, Copy, CheckCircle2, ShieldCheck, FileKey } from "lucide-react";

export default async function EvidenceDetailPage({ params }: { params: { id: string } }) {
  const id = params.id;

  return (
    <div className="flex flex-col h-full overflow-hidden">
      
      {/* Top Header */}
      <div className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between shrink-0 sticky top-0 z-10 shadow-sm">
        <div>
          <Breadcrumb />
          <div className="flex items-center gap-3 mt-1">
            <h1 className="text-xl font-bold text-gray-900">{id}</h1>
            <StatusBadge variant="success">Ready</StatusBadge>
          </div>
        </div>
      </div>

      {/* Split Pane Workspace */}
      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
        
        {/* LEFT PANEL (70%) */}
        <div className="w-full lg:w-[70%] lg:border-r border-gray-200 bg-[#FAFAFA] flex flex-col overflow-hidden p-6 space-y-6 overflow-y-auto">
          
          <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm shrink-0">
            <h2 className="text-sm font-semibold text-gray-900 mb-4 border-b border-gray-100 pb-3">Package Summary</h2>
            <div className="grid grid-cols-2 lg:grid-cols-3 gap-y-4 gap-x-6">
              <div>
                <p className="text-xs text-gray-500 mb-1">Package ID</p>
                <p className="text-sm font-medium text-gray-900">{id}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Period</p>
                <p className="text-sm font-medium text-gray-900">April 2025</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Status</p>
                <p className="text-sm font-medium text-green-600">Ready</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Generated By</p>
                <p className="text-sm font-medium text-gray-900">Alex Brown</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Generated At</p>
                <p className="text-sm font-medium text-gray-900">May 1, 2025 10:00 AM</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Size</p>
                <p className="text-sm font-medium text-gray-900">45.2 MB</p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm shrink-0">
            <h2 className="text-sm font-semibold text-gray-900 mb-4 border-b border-gray-100 pb-3">Generation Timeline</h2>
            <div className="relative border-l border-gray-200 ml-3 space-y-6 py-2">
              <div className="relative flex items-center">
                <div className="absolute -left-[5px] h-2.5 w-2.5 rounded-full bg-blue-500 ring-4 ring-white" />
                <div className="ml-6 flex items-center justify-between w-full">
                  <span className="text-sm font-medium text-gray-900">Requested</span>
                  <span className="text-xs text-gray-500">May 1, 2025 09:55 AM</span>
                </div>
              </div>
              <div className="relative flex items-center">
                <div className="absolute -left-[5px] h-2.5 w-2.5 rounded-full bg-blue-500 ring-4 ring-white" />
                <div className="ml-6 flex items-center justify-between w-full">
                  <span className="text-sm font-medium text-gray-900">Started</span>
                  <span className="text-xs text-gray-500">May 1, 2025 09:56 AM</span>
                </div>
              </div>
              <div className="relative flex items-center">
                <div className="absolute -left-[5px] h-2.5 w-2.5 rounded-full bg-blue-500 ring-4 ring-white" />
                <div className="ml-6 flex items-center justify-between w-full">
                  <span className="text-sm font-medium text-gray-900">Completed</span>
                  <span className="text-xs text-gray-500">May 1, 2025 10:00 AM</span>
                </div>
              </div>
              <div className="relative flex items-center">
                <div className="absolute -left-[5px] h-2.5 w-2.5 rounded-full bg-gray-300 ring-4 ring-white" />
                <div className="ml-6 flex items-center justify-between w-full">
                  <span className="text-sm font-medium text-gray-500">Downloaded</span>
                  <span className="text-xs text-gray-400">Not yet</span>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm flex-1">
            <h2 className="text-sm font-semibold text-gray-900 mb-4 border-b border-gray-100 pb-3">Package Contents</h2>
            <EvidenceDetailClient />
          </div>

        </div>

        {/* RIGHT PANEL (30%) */}
        <div className="w-full lg:w-[30%] bg-white flex flex-col border-t lg:border-t-0 border-gray-200 h-[600px] lg:h-auto overflow-y-auto">
          
          <div className="p-5 border-b border-gray-200 shrink-0">
            <h2 className="text-sm font-semibold text-gray-900 mb-4">Package Health</h2>
            <div className="space-y-3">
              <div className="flex justify-between items-center py-2 border-b border-gray-50">
                <span className="text-sm text-gray-600">Status</span>
                <span className="font-medium text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3.5 h-3.5"/> Ready</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-gray-50">
                <span className="text-sm text-gray-600">Expiry</span>
                <span className="font-medium text-gray-900">May 31, 2025 (22 days left)</span>
              </div>
              <div className="flex justify-between items-center py-2">
                <span className="text-sm text-gray-600">Download Count</span>
                <span className="font-medium text-gray-900">0</span>
              </div>
            </div>
          </div>

          <div className="p-5 border-b border-gray-200 shrink-0">
            <h2 className="text-sm font-semibold text-gray-900 mb-4">Actions</h2>
            <div className="space-y-2 flex flex-col">
              <Button className="justify-start bg-blue-600 hover:bg-blue-700 text-white">
                <Download className="mr-2 h-4 w-4" aria-hidden="true" /> Download Package
              </Button>
              <Button variant="outline" className="justify-start text-gray-700">
                <RefreshCw className="mr-2 h-4 w-4" aria-hidden="true" /> Regenerate Package
              </Button>
              <Button variant="outline" className="justify-start text-gray-700">
                <Copy className="mr-2 h-4 w-4" aria-hidden="true" /> Copy Package ID
              </Button>
            </div>
          </div>

          <div className="p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-4">Integrity</h2>
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <ShieldCheck className="h-5 w-5 text-green-500 shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-gray-900">Valid Checksum</p>
                  <p className="text-xs text-gray-500 font-mono mt-0.5 break-all">sha256: 8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <FileKey className="h-4 w-4 text-gray-500 shrink-0" />
                <p className="text-sm font-medium text-gray-900">Manifest Present</p>
              </div>
              <div className="flex items-center gap-3">
                <FileKey className="h-4 w-4 text-gray-500 shrink-0" />
                <p className="text-sm font-medium text-gray-900">Audit Ledger Present</p>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
