import { CanonicalTransactionInput } from "../ingestion/types";
import { MatchCandidate, MatchingStrategy, ReconciliationConfig, ReconciliationResult } from "./types";
import { ExactStrategy } from "./strategies/exact";
import { ToleranceStrategy } from "./strategies/tolerance";
import { CompositeStrategy } from "./strategies/composite";

export class ReconciliationEngine {
  private config: ReconciliationConfig;
  private strategies: MatchingStrategy[];

  constructor(config: ReconciliationConfig) {
    this.config = config;
    // Order matters for performance, not necessarily for confidence since we score all candidates
    // but Exact is fastest so it goes first.
    this.strategies = [
      new ExactStrategy(),
      new ToleranceStrategy(),
      new CompositeStrategy()
    ];
  }

  public runReconciliation(
    sourceRecords: CanonicalTransactionInput[],
    targetRecords: CanonicalTransactionInput[]
  ): ReconciliationResult[] {
    
    const results: ReconciliationResult[] = [];
    
    // Track which target records have already been matched to enforce 1-to-1 locking
    const claimedTargetIds = new Set<string>();

    for (const sourceTx of sourceRecords) {
      // Filter out targets that have already been claimed in this run
      const availableTargets = targetRecords.filter(t => !claimedTargetIds.has(t.platformId!));

      const candidates: MatchCandidate[] = [];

      // 1. Generate Candidate Set
      for (const strategy of this.strategies) {
        const stratCandidates = strategy.findCandidates(sourceTx, availableTargets, this.config);
        candidates.push(...stratCandidates);
      }

      // 2. Filter by threshold and Sort
      const viableCandidates = candidates
        .filter(c => c.finalConfidence >= this.config.minimumConfidenceThreshold)
        .sort((a, b) => b.finalConfidence - a.finalConfidence); // Descending score

      // 3. Selection & Ambiguity Detection
      if (viableCandidates.length === 0) {
        // UNMATCHED
        results.push({
          sourceTx,
          status: "UNMATCHED",
          confidenceScore: 0,
          amountVariance: 0,
          evidenceTrail: [
            candidates.length > 0 
              ? `No candidate exceeded the minimum threshold of ${this.config.minimumConfidenceThreshold}. Best candidate scored ${candidates.sort((a,b) => b.finalConfidence - a.finalConfidence)[0].finalConfidence.toFixed(2)}.`
              : `Evaluated against ${availableTargets.length} candidate records. No matches generated by any strategy.`
          ]
        });
      } else if (viableCandidates.length > 1 && viableCandidates[0].finalConfidence === viableCandidates[1].finalConfidence) {
        // AMBIGUOUS: Multiple candidates tied for highest score
        results.push({
          sourceTx,
          status: "AMBIGUOUS",
          confidenceScore: viableCandidates[0].finalConfidence,
          amountVariance: 0, // Variance is unclear since we didn't pick one
          evidenceTrail: [
            `Multiple candidates achieved identical high score (${viableCandidates[0].finalConfidence.toFixed(2)}).`,
            `Tied Candidates: [${viableCandidates.filter(c => c.finalConfidence === viableCandidates[0].finalConfidence).map(c => c.targetTx.platformId).join(", ")}].`
          ]
        });
      } else {
        // MATCHED: We have a clear winner
        const winner = viableCandidates[0];
        
        let status: ReconciliationResult["status"] = "MATCHED";
        if (winner.strategyUsed === "TOLERANCE") {
          status = "MATCHED_WITH_TOLERANCE";
        } else if (winner.strategyUsed === "COMPOSITE") {
          // Composite matches lack an exact docNumber, so it's technically a fuzzy/derived match.
          // In the user's revised design, we map it to MATCHED_WITH_TOLERANCE to indicate it wasn't a 100% clean pair.
          status = "MATCHED_WITH_TOLERANCE";
        }

        // 1-to-1 Lock Target
        claimedTargetIds.add(winner.targetTx.platformId!);

        results.push({
          sourceTx,
          targetTx: winner.targetTx,
          status,
          strategyUsed: winner.strategyUsed,
          confidenceScore: winner.finalConfidence,
          amountVariance: winner.amountVariance,
          evidenceTrail: winner.evidence
        });
      }
    }

    return results;
  }
}
